require 'spec_helper'
require 'ffi/ffmpeg'
require 'ffi/ffmpeg/api/av_codec_id'


describe 'FFI::FFmpeg::AVCodecID' do
  subject { FFI::FFmpeg::AVCodecID }

  it 'defines an enum' do
    subject.should be_a FFI::Enum
  end

  context 'default enum values' do
    specify { subject[:none].should               == 0 }
    specify { subject[:mpeg1_video].should        == 1 }
    specify { subject[:mpeg2_video].should        == 2 }
    specify { subject[:mpeg2_video_xvmc].should   == 3 }
    specify { subject[:h261].should               == 4 }
    specify { subject[:h263].should               == 5 }
    specify { subject[:rv10].should               == 6 }
    specify { subject[:rv20].should               == 7 }
    specify { subject[:mjpeg].should              == 8 }
    specify { subject[:mjpegb].should             == 9 }
    specify { subject[:ljpeg].should              == 10 }
    specify { subject[:sp5x].should               == 11 }
    specify { subject[:jpeg_ls].should            == 12 }
    specify { subject[:mpeg4].should              == 13 }
    specify { subject[:rawvideo].should           == 14 }
    specify { subject[:ms_mpeg4_v1].should        == 15 }
    specify { subject[:ms_mpeg4_v2].should        == 16 }
    specify { subject[:ms_mpeg4_v3].should        == 17 }
    specify { subject[:wmv1].should               == 18 }
    specify { subject[:wmv2].should               == 19 }
    specify { subject[:h263p].should              == 20 }
    specify { subject[:h263i].should              == 21 }
    specify { subject[:flv1].should               == 22 }
    specify { subject[:svq1].should               == 23 }
    specify { subject[:svq3].should               == 24 }
    specify { subject[:dv_video].should           == 25 }
    specify { subject[:huffyuv].should            == 26 }
    specify { subject[:cyuv].should               == 27 }
    specify { subject[:h264].should               == 28 }
    specify { subject[:indeo3].should             == 29 }
    specify { subject[:vp3].should                == 30 }
    specify { subject[:theora].should             == 31 }
    specify { subject[:asv1].should               == 32 }
    specify { subject[:asv2].should               == 33 }
    specify { subject[:ffv1].should               == 34 }
    specify { subject[:fourxm].should             == 35 }
    specify { subject[:vcr1].should               == 36 }
    specify { subject[:cljr].should               == 37 }
    specify { subject[:mdec].should               == 38 }
    specify { subject[:roq].should                == 39 }
    specify { subject[:interplay_video].should    == 40 }
    specify { subject[:xan_wc3].should            == 41 }
    specify { subject[:xan_wc4].should            == 42 }
    specify { subject[:rpza].should               == 43 }
    specify { subject[:cinepak].should            == 44 }
    specify { subject[:ws_vqa].should             == 45 }
    specify { subject[:msrle].should              == 46 }
    specify { subject[:msvideo1].should           == 47 }
    specify { subject[:idcin].should              == 48 }
    specify { subject[:eightbps].should           == 49 }
    specify { subject[:smc].should                == 50 }
    specify { subject[:flic].should               == 51 }
    specify { subject[:truemotion1].should        == 52 }
    specify { subject[:vmdvideo].should           == 53 }
    specify { subject[:mszh].should               == 54 }
    specify { subject[:zlib].should               == 55 }
    specify { subject[:qtrle].should              == 56 }
    specify { subject[:snow].should               == 57 }
    specify { subject[:tscc].should               == 58 }
    specify { subject[:ulti].should               == 59 }
    specify { subject[:qdraw].should              == 60 }
    specify { subject[:vixl].should               == 61 }
    specify { subject[:qpeg].should               == 62 }
    specify { subject[:png].should                == 63 }
    specify { subject[:ppm].should                == 64 }
    specify { subject[:pbm].should                == 65 }
    specify { subject[:pgm].should                == 66 }
    specify { subject[:pgmyuv].should             == 67 }
    specify { subject[:pam].should                == 68 }
    specify { subject[:ffvhuff].should            == 69 }
    specify { subject[:rv30].should               == 70 }
    specify { subject[:rv40].should               == 71 }
    specify { subject[:vc1].should                == 72 }
    specify { subject[:wmv3].should               == 73 }
    specify { subject[:loco].should               == 74 }
    specify { subject[:wnv1].should               == 75 }
    specify { subject[:aasc].should               == 76 }
    specify { subject[:indeo2].should             == 77 }
    specify { subject[:fraps].should              == 78 }
    specify { subject[:truemotion2].should        == 79 }
    specify { subject[:bmp].should                == 80 }
    specify { subject[:cscd].should               == 81 }
    specify { subject[:mmvideo].should            == 82 }
    specify { subject[:zmbv].should               == 83 }
    specify { subject[:avs].should                == 84 }
    specify { subject[:smackvideo].should         == 85 }
    specify { subject[:nuv].should                == 86 }
    specify { subject[:kmvc].should               == 87 }
    specify { subject[:flashsv].should            == 88 }
    specify { subject[:cavs].should               == 89 }
    specify { subject[:jpeg2000].should           == 90 }
    specify { subject[:vmnc].should               == 91 }
    specify { subject[:vp5].should                == 92 }
    specify { subject[:vp6].should                == 93 }
    specify { subject[:vp6f].should               == 94 }
    specify { subject[:targa].should              == 95 }
    specify { subject[:dsicinvideo].should        == 96 }
    specify { subject[:tiertexseqvideo].should    == 97 }
    specify { subject[:tiff].should               == 98 }
    specify { subject[:gif].should                == 99 }
    specify { subject[:dxa].should                == 100 }
    specify { subject[:dnxhd].should              == 101 }
    specify { subject[:thp].should                == 102 }
    specify { subject[:sgi].should                == 103 }
    specify { subject[:c93].should                == 104 }
    specify { subject[:bethsoftvid].should        == 105 }
    specify { subject[:ptx].should                == 106 }
    specify { subject[:txd].should                == 107 }
    specify { subject[:vp6a].should               == 108 }
    specify { subject[:amv].should                == 109 }
    specify { subject[:vb].should                 == 110 }
    specify { subject[:pcx].should                == 111 }
    specify { subject[:sunrast].should            == 112 }
    specify { subject[:indeo4].should             == 113 }
    specify { subject[:indeo5].should             == 114 }
    specify { subject[:mimic].should              == 115 }
    specify { subject[:rl2].should                == 116 }
    specify { subject[:escape124].should          == 117 }
    specify { subject[:dirac].should              == 118 }
    specify { subject[:bfi].should                == 119 }
    specify { subject[:cmv].should                == 120 }
    specify { subject[:motionpixels].should       == 121 }
    specify { subject[:tgv].should                == 122 }
    specify { subject[:tgq].should                == 123 }
    # what goes here?
    specify { subject[:aura].should               == 125 }
    specify { subject[:aura2].should              == 126 }
    specify { subject[:v210x].should              == 127 }
    specify { subject[:tmv].should                == 128 }
    specify { subject[:v210].should               == 129 }
    specify { subject[:dpx].should                == 130 }
    specify { subject[:mad].should                == 131 }
    specify { subject[:frwu].should               == 132 }
    specify { subject[:flashsv2].should           == 133 }
    specify { subject[:cdgraphics].should         == 134 }
    specify { subject[:r210].should               == 135 }
    specify { subject[:anm].should                == 136 }
    specify { subject[:binkvideo].should          == 137 }
    specify { subject[:iff_ilbm].should           == 138 }
    specify { subject[:iff_byterun1].should       == 139 }
    specify { subject[:kgv1].should               == 140 }
    specify { subject[:yop].should                == 141 }
    specify { subject[:vp8].should                == 142 }
    specify { subject[:pictor].should             == 143 }
    specify { subject[:ansi].should               == 144 }
    specify { subject[:a64_multi].should          == 145 }
    specify { subject[:a64_multi5].should         == 146 }
    specify { subject[:r10k].should               == 147 }
    specify { subject[:mxpeg].should              == 148 }
    specify { subject[:lagarith].should           == 149 }
    specify { subject[:prores].should             == 150 }
    specify { subject[:jv].should                 == 151 }
    specify { subject[:dfa].should                == 152 }
    specify { subject[:wmv3image].should          == 153 }
    specify { subject[:vc1image].should           == 154 }
    specify { subject[:utvideo].should            == 155 }
    specify { subject[:bmv_video].should          == 156 }
    specify { subject[:vble].should               == 157 }
    specify { subject[:dxtory].should             == 158 }
    specify { subject[:v410].should               == 159 }
    specify { subject[:xwd].should                == 160 }
    specify { subject[:cdxl].should               == 161 }
    specify { subject[:xbm].should                == 162 }
    specify { subject[:zerocodec].should          == 163 }
    specify { subject[:mss1].should               == 164 }
    specify { subject[:msa1].should               == 165 }
    specify { subject[:tscc2].should              == 166 }
    specify { subject[:mts2].should               == 167 }
    specify { subject[:cllc].should               == 168 }
    specify { subject[:mss2].should               == 169 }
    specify { subject[:brender_pix].should        == 170 }
    specify { subject[:y41p].should               == 171 }
    specify { subject[:escape130].should          == 172 }
    specify { subject[:exr].should                == 173 }
    specify { subject[:avrp].should               == 174 }
    specify { subject[:g2m].should                == 175 }
    specify { subject[:avui].should               == 176 }
    specify { subject[:ayuv].should               == 177 }
    specify { subject[:targa_y216].should         == 178 }
    specify { subject[:v308].should               == 179 }
    specify { subject[:v408].should               == 180 }
    specify { subject[:sanm].should               == 181 }
    specify { subject[:paf_video].should          == 182 }
    specify { subject[:avrn].should               == 183 }
    specify { subject[:cpia].should               == 184 }
    specify { subject[:xface].should              == 185 }
    specify { subject[:sgirle].should             == 186 }
    specify { subject[:mvc1].should               == 187 }
    specify { subject[:mvc2].should               == 188 }

    # audio
    specify { subject[:first_audio].should        == 189 }
    specify { subject[:pcm_s16le].should          == 190 }
    specify { subject[:pcm_s16be].should          == 191 }
    specify { subject[:pcm_u16le].should          == 192 }
    specify { subject[:pcm_u16be].should          == 193 }
    specify { subject[:pcm_s8].should             == 194 }
    specify { subject[:pcm_u8].should             == 195 }
    specify { subject[:pcm_mulaw].should          == 196 }
    specify { subject[:pcm_alaw].should           == 197 }
    specify { subject[:pcm_s32le].should          == 198 }
    specify { subject[:pcm_s32be].should          == 199 }
    specify { subject[:pcm_u32le].should          == 200 }
    specify { subject[:pcm_u32be].should          == 201 }
    specify { subject[:pcm_s24le].should          == 202 }
    specify { subject[:pcm_s24be].should          == 203 }
    specify { subject[:pcm_u24le].should          == 204 }
    specify { subject[:pcm_u24be].should          == 205 }
    specify { subject[:pcm_s24daud].should        == 206 }
    specify { subject[:pcm_zork].should           == 207 }
    specify { subject[:pcm_s16le_planar].should   == 208 }
    specify { subject[:pcm_dvd].should            == 209 }
    specify { subject[:pcm_f32be].should          == 210 }
    specify { subject[:pcm_f32le].should          == 211 }
    specify { subject[:pcm_f64be].should          == 212 }
    specify { subject[:pcm_f64le].should          == 213 }
    specify { subject[:pcm_bluray].should         == 214 }
    specify { subject[:pcm_lxf].should            == 215 }
    specify { subject[:s302m].should              == 216 }
    specify { subject[:pcm_s8_planar].should      == 217 }
    specify { subject[:pcm_s42le_planar].should   == 218 }
    specify { subject[:pcm_s32le_planar].should   == 219 }
    specify { subject[:pcm_s16be_planar].should   == 220 }
    specify { subject[:adpcm_ima_qt].should       == 221 }
    specify { subject[:adpcm_ima_wav].should      == 222 }
    specify { subject[:adpcm_ima_dk3].should      == 223 }
    specify { subject[:adpcm_ima_dk4].should      == 224 }
    specify { subject[:adpcm_ima_ws].should       == 225 }
    specify { subject[:adpcm_ima_smjpeg].should   == 226 }
    specify { subject[:adpcm_ms].should           == 227 }
    specify { subject[:adpcm_4xm].should          == 228 }
    specify { subject[:adpcm_xa].should           == 229 }
    specify { subject[:adpcm_adx].should          == 230 }
    specify { subject[:adpcm_ea].should           == 231 }
    specify { subject[:adpcm_g726].should         == 232 }
    specify { subject[:adpcm_ct].should           == 233 }
    specify { subject[:adpcm_swf].should          == 234 }
    specify { subject[:adpcm_yamaha].should       == 235 }
    specify { subject[:adpcm_sbpro_4].should      == 236 }
    specify { subject[:adpcm_sbpro_3].should      == 237 }
    specify { subject[:adpcm_sbpro_2].should      == 238 }
    specify { subject[:adpcm_thp].should          == 239 }
    specify { subject[:adpcm_ima_amv].should      == 240 }
    specify { subject[:adpcm_ea_r1].should        == 241 }
    specify { subject[:adpcm_ea_r3].should        == 242 }
    specify { subject[:adpcm_ea_r2].should        == 243 }
    specify { subject[:adpcm_ima_ea_sead].should  == 244 }
    specify { subject[:adpcm_ima_ea_eacs].should  == 245 }
    specify { subject[:adpcm_ea_xas].should       == 246 }
    specify { subject[:adpcm_ea_maxis_xa].should  == 247 }
    specify { subject[:adpcm_ima_iss].should      == 248 }
    specify { subject[:adpcm_g722].should         == 249 }
    specify { subject[:adpcm_ima_apc].should      == 250 }
    specify { subject[:vima].should               == 251 }
    specify { subject[:adpcm_afc].should          == 252 }
    specify { subject[:adpcm_ima_oki].should      == 253 }
    specify { subject[:amr_nb].should             == 254 }
    specify { subject[:amr_wb].should             == 255 }
    specify { subject[:ra_144].should             == 256 }
    specify { subject[:ra_288].should             == 257 }
    specify { subject[:roq_dpcm].should           == 258 }
    specify { subject[:interplay_dpcm].should     == 259 }
    specify { subject[:xan_dpcm].should           == 260 }
    specify { subject[:sol_dpcm].should           == 261 }
    specify { subject[:mp2].should                == 262 }
    specify { subject[:mp3].should                == 263 }
    specify { subject[:aac].should                == 264 }
    specify { subject[:ac3].should                == 265 }
    specify { subject[:dts].should                == 266 }
    specify { subject[:vorbis].should             == 267 }
    specify { subject[:dvaudio].should            == 268 }
    specify { subject[:wmav1].should              == 269 }
    specify { subject[:wmav2].should              == 270 }
    specify { subject[:mace3].should              == 271 }
    specify { subject[:mace6].should              == 272 }
    specify { subject[:flac].should               == 273 }
    specify { subject[:mp3adu].should             == 274 }
    specify { subject[:mp3on4].should             == 275 }
    specify { subject[:shorten].should            == 276 }
    specify { subject[:alac].should               == 277 }
    specify { subject[:westwood_snd1].should      == 278 }
    specify { subject[:gsm].should                == 279 }
    specify { subject[:qdm2].should               == 280 }
    specify { subject[:cook].should               == 281 }
    specify { subject[:truespeech].should         == 282 }
    specify { subject[:tta].should                == 283 }
    specify { subject[:smackaudio].should         == 284 }
    specify { subject[:qcelp].should              == 285 }
    specify { subject[:wavpack].should            == 286 }
    specify { subject[:dsicinaudio].should        == 287 }
    specify { subject[:imc].should                == 288 }
    specify { subject[:musepack7].should          == 289 }
    specify { subject[:mlp].should                == 290 }
    specify { subject[:gsm_ms].should             == 291 }
    specify { subject[:atrac3].should             == 292 }
    specify { subject[:voxware].should            == 293 }
    specify { subject[:ape].should                == 294 }
    specify { subject[:nellymoser].should         == 295 }
    specify { subject[:musepack8].should          == 296 }
    specify { subject[:speex].should              == 297 }
    specify { subject[:wmavoice].should           == 298 }
    specify { subject[:wmapro].should             == 299 }
    specify { subject[:wmalossless].should        == 300 }
    specify { subject[:atrac3p].should            == 301 }
    specify { subject[:eac3].should               == 302 }
    specify { subject[:sipr].should               == 303 }
    specify { subject[:mp1].should                == 304 }
    specify { subject[:twinvq].should             == 305 }
    specify { subject[:truehd].should             == 306 }
    specify { subject[:mp4als].should             == 307 }
    specify { subject[:atrac1].should             == 308 }
    specify { subject[:binkaudio_rdft].should     == 309 }
    specify { subject[:binkaudio_dct].should      == 310 }
    specify { subject[:aac_latm].should           == 311 }
    specify { subject[:qdmc].should               == 312 }
    specify { subject[:celt].should               == 313 }
    specify { subject[:g732_1].should             == 314 }
    specify { subject[:g729].should               == 315 }
    specify { subject[:eightsvx_exp].should       == 316 }
    specify { subject[:eightsvx_fib].should       == 317 }
    specify { subject[:bmv_audio].should          == 318 }
    specify { subject[:ralf].should               == 319 }
    specify { subject[:iac].should                == 320 }
    specify { subject[:ilbc].should               == 321 }
    specify { subject[:opus_deprecated].should    == 322 }
    specify { subject[:comfort_noise].should      == 323 }
    specify { subject[:tak_deprecated].should     == 324 }
    specify { subject[:ffwavesynth].should        == 325 }
    specify { subject[:eightsvx_raw].should       == 326 }
    specify { subject[:sonic].should              == 327 }
    specify { subject[:sonic_ls].should           == 328 }
    specify { subject[:paf_audio].should          == 329 }
    specify { subject[:opus].should               == 330 }
    specify { subject[:tak].should                == 331 }

    # subtitles
    specify { subject[:first_subtitle].should     == 332 }
    specify { subject[:dvd_subtitle].should       == 333 }
    specify { subject[:dvb_subtitle].should       == 334 }
    specify { subject[:text].should               == 335 }
    specify { subject[:xsub].should               == 336 }
    specify { subject[:ssa].should                == 337 }
    specify { subject[:mov_text].should           == 338 }
    specify { subject[:hdmv_pgs_subtitle].should  == 339 }
    specify { subject[:dvb_teletext].should       == 340 }
    specify { subject[:srt].should                == 341 }
    specify { subject[:microdvd].should           == 342 }
    specify { subject[:eia_608].should            == 343 }
    specify { subject[:jacosub].should            == 344 }
    specify { subject[:sami].should               == 345 }
    specify { subject[:realtext].should           == 346 }
    specify { subject[:subviewer].should          == 347 }
    specify { subject[:subrip].should             == 348 }
    specify { subject[:webvtt].should             == 349 }
    specify { subject[:first_unknown].should      == 350 }
    specify { subject[:ttf].should                == 351 }
    specify { subject[:bintext].should            == 352 }
    specify { subject[:xbin].should               == 353 }
    specify { subject[:idf].should                == 354 }
    specify { subject[:otf].should                == 355 }
    specify { subject[:smpte_klv].should          == 356 }
    specify { subject[:probe].should              == 357 }
    specify { subject[:mpeg2ts].should            == 358 }
    specify { subject[:mpeg4systems].should       == 359 }
    specify { subject[:fmetadata].should be_nil }
  end
end
